services:
  - type: web
    name: tds-fastapi-app
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: UVICORN_PORT
        value: 10000
    plan: free
