services:
  - type: web
    name: tds-2025-05-project-1
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.answer:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PORT
        value: 10000
